/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MainGetPlacementsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MainGetPlacementsRequest{}

// MainGetPlacementsRequest struct for MainGetPlacementsRequest
type MainGetPlacementsRequest struct {
	// Resource requirements for the Machine to simulate. Defaults to a performance-1x machine
	Compute *FlyMachineGuest `json:"compute,omitempty"`
	// Number of machines to simulate placement. Defaults to 0, which returns the org-specific limit for each region.
	Count *int32 `json:"count,omitempty"`
	OrgSlug string `json:"org_slug"`
	// Region expression for placement as a comma-delimited set of regions or aliases. Defaults to \"[region],any\", to prefer the API endpoint's local region with any other region as fallback.
	Region *string `json:"region,omitempty"`
	VolumeName *string `json:"volume_name,omitempty"`
	VolumeSizeBytes *int32 `json:"volume_size_bytes,omitempty"`
	// Optional weights to override default placement preferences.
	Weights *map[string]int32 `json:"weights,omitempty"`
}

type _MainGetPlacementsRequest MainGetPlacementsRequest

// NewMainGetPlacementsRequest instantiates a new MainGetPlacementsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMainGetPlacementsRequest(orgSlug string) *MainGetPlacementsRequest {
	this := MainGetPlacementsRequest{}
	this.OrgSlug = orgSlug
	return &this
}

// NewMainGetPlacementsRequestWithDefaults instantiates a new MainGetPlacementsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMainGetPlacementsRequestWithDefaults() *MainGetPlacementsRequest {
	this := MainGetPlacementsRequest{}
	return &this
}

// GetCompute returns the Compute field value if set, zero value otherwise.
func (o *MainGetPlacementsRequest) GetCompute() FlyMachineGuest {
	if o == nil || IsNil(o.Compute) {
		var ret FlyMachineGuest
		return ret
	}
	return *o.Compute
}

// GetComputeOk returns a tuple with the Compute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainGetPlacementsRequest) GetComputeOk() (*FlyMachineGuest, bool) {
	if o == nil || IsNil(o.Compute) {
		return nil, false
	}
	return o.Compute, true
}

// HasCompute returns a boolean if a field has been set.
func (o *MainGetPlacementsRequest) HasCompute() bool {
	if o != nil && !IsNil(o.Compute) {
		return true
	}

	return false
}

// SetCompute gets a reference to the given FlyMachineGuest and assigns it to the Compute field.
func (o *MainGetPlacementsRequest) SetCompute(v FlyMachineGuest) {
	o.Compute = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *MainGetPlacementsRequest) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainGetPlacementsRequest) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *MainGetPlacementsRequest) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *MainGetPlacementsRequest) SetCount(v int32) {
	o.Count = &v
}

// GetOrgSlug returns the OrgSlug field value
func (o *MainGetPlacementsRequest) GetOrgSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgSlug
}

// GetOrgSlugOk returns a tuple with the OrgSlug field value
// and a boolean to check if the value has been set.
func (o *MainGetPlacementsRequest) GetOrgSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgSlug, true
}

// SetOrgSlug sets field value
func (o *MainGetPlacementsRequest) SetOrgSlug(v string) {
	o.OrgSlug = v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *MainGetPlacementsRequest) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainGetPlacementsRequest) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *MainGetPlacementsRequest) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *MainGetPlacementsRequest) SetRegion(v string) {
	o.Region = &v
}

// GetVolumeName returns the VolumeName field value if set, zero value otherwise.
func (o *MainGetPlacementsRequest) GetVolumeName() string {
	if o == nil || IsNil(o.VolumeName) {
		var ret string
		return ret
	}
	return *o.VolumeName
}

// GetVolumeNameOk returns a tuple with the VolumeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainGetPlacementsRequest) GetVolumeNameOk() (*string, bool) {
	if o == nil || IsNil(o.VolumeName) {
		return nil, false
	}
	return o.VolumeName, true
}

// HasVolumeName returns a boolean if a field has been set.
func (o *MainGetPlacementsRequest) HasVolumeName() bool {
	if o != nil && !IsNil(o.VolumeName) {
		return true
	}

	return false
}

// SetVolumeName gets a reference to the given string and assigns it to the VolumeName field.
func (o *MainGetPlacementsRequest) SetVolumeName(v string) {
	o.VolumeName = &v
}

// GetVolumeSizeBytes returns the VolumeSizeBytes field value if set, zero value otherwise.
func (o *MainGetPlacementsRequest) GetVolumeSizeBytes() int32 {
	if o == nil || IsNil(o.VolumeSizeBytes) {
		var ret int32
		return ret
	}
	return *o.VolumeSizeBytes
}

// GetVolumeSizeBytesOk returns a tuple with the VolumeSizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainGetPlacementsRequest) GetVolumeSizeBytesOk() (*int32, bool) {
	if o == nil || IsNil(o.VolumeSizeBytes) {
		return nil, false
	}
	return o.VolumeSizeBytes, true
}

// HasVolumeSizeBytes returns a boolean if a field has been set.
func (o *MainGetPlacementsRequest) HasVolumeSizeBytes() bool {
	if o != nil && !IsNil(o.VolumeSizeBytes) {
		return true
	}

	return false
}

// SetVolumeSizeBytes gets a reference to the given int32 and assigns it to the VolumeSizeBytes field.
func (o *MainGetPlacementsRequest) SetVolumeSizeBytes(v int32) {
	o.VolumeSizeBytes = &v
}

// GetWeights returns the Weights field value if set, zero value otherwise.
func (o *MainGetPlacementsRequest) GetWeights() map[string]int32 {
	if o == nil || IsNil(o.Weights) {
		var ret map[string]int32
		return ret
	}
	return *o.Weights
}

// GetWeightsOk returns a tuple with the Weights field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainGetPlacementsRequest) GetWeightsOk() (*map[string]int32, bool) {
	if o == nil || IsNil(o.Weights) {
		return nil, false
	}
	return o.Weights, true
}

// HasWeights returns a boolean if a field has been set.
func (o *MainGetPlacementsRequest) HasWeights() bool {
	if o != nil && !IsNil(o.Weights) {
		return true
	}

	return false
}

// SetWeights gets a reference to the given map[string]int32 and assigns it to the Weights field.
func (o *MainGetPlacementsRequest) SetWeights(v map[string]int32) {
	o.Weights = &v
}

func (o MainGetPlacementsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MainGetPlacementsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Compute) {
		toSerialize["compute"] = o.Compute
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	toSerialize["org_slug"] = o.OrgSlug
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.VolumeName) {
		toSerialize["volume_name"] = o.VolumeName
	}
	if !IsNil(o.VolumeSizeBytes) {
		toSerialize["volume_size_bytes"] = o.VolumeSizeBytes
	}
	if !IsNil(o.Weights) {
		toSerialize["weights"] = o.Weights
	}
	return toSerialize, nil
}

func (o *MainGetPlacementsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"org_slug",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMainGetPlacementsRequest := _MainGetPlacementsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMainGetPlacementsRequest)

	if err != nil {
		return err
	}

	*o = MainGetPlacementsRequest(varMainGetPlacementsRequest)

	return err
}

type NullableMainGetPlacementsRequest struct {
	value *MainGetPlacementsRequest
	isSet bool
}

func (v NullableMainGetPlacementsRequest) Get() *MainGetPlacementsRequest {
	return v.value
}

func (v *NullableMainGetPlacementsRequest) Set(val *MainGetPlacementsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMainGetPlacementsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMainGetPlacementsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMainGetPlacementsRequest(val *MainGetPlacementsRequest) *NullableMainGetPlacementsRequest {
	return &NullableMainGetPlacementsRequest{value: val, isSet: true}
}

func (v NullableMainGetPlacementsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMainGetPlacementsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


