/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the FlyMachineMount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlyMachineMount{}

// FlyMachineMount struct for FlyMachineMount
type FlyMachineMount struct {
	AddSizeGb *int32 `json:"add_size_gb,omitempty"`
	Encrypted *bool `json:"encrypted,omitempty"`
	ExtendThresholdPercent *int32 `json:"extend_threshold_percent,omitempty"`
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
	SizeGb *int32 `json:"size_gb,omitempty"`
	SizeGbLimit *int32 `json:"size_gb_limit,omitempty"`
	Volume *string `json:"volume,omitempty"`
}

// NewFlyMachineMount instantiates a new FlyMachineMount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlyMachineMount() *FlyMachineMount {
	this := FlyMachineMount{}
	return &this
}

// NewFlyMachineMountWithDefaults instantiates a new FlyMachineMount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlyMachineMountWithDefaults() *FlyMachineMount {
	this := FlyMachineMount{}
	return &this
}

// GetAddSizeGb returns the AddSizeGb field value if set, zero value otherwise.
func (o *FlyMachineMount) GetAddSizeGb() int32 {
	if o == nil || IsNil(o.AddSizeGb) {
		var ret int32
		return ret
	}
	return *o.AddSizeGb
}

// GetAddSizeGbOk returns a tuple with the AddSizeGb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyMachineMount) GetAddSizeGbOk() (*int32, bool) {
	if o == nil || IsNil(o.AddSizeGb) {
		return nil, false
	}
	return o.AddSizeGb, true
}

// HasAddSizeGb returns a boolean if a field has been set.
func (o *FlyMachineMount) HasAddSizeGb() bool {
	if o != nil && !IsNil(o.AddSizeGb) {
		return true
	}

	return false
}

// SetAddSizeGb gets a reference to the given int32 and assigns it to the AddSizeGb field.
func (o *FlyMachineMount) SetAddSizeGb(v int32) {
	o.AddSizeGb = &v
}

// GetEncrypted returns the Encrypted field value if set, zero value otherwise.
func (o *FlyMachineMount) GetEncrypted() bool {
	if o == nil || IsNil(o.Encrypted) {
		var ret bool
		return ret
	}
	return *o.Encrypted
}

// GetEncryptedOk returns a tuple with the Encrypted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyMachineMount) GetEncryptedOk() (*bool, bool) {
	if o == nil || IsNil(o.Encrypted) {
		return nil, false
	}
	return o.Encrypted, true
}

// HasEncrypted returns a boolean if a field has been set.
func (o *FlyMachineMount) HasEncrypted() bool {
	if o != nil && !IsNil(o.Encrypted) {
		return true
	}

	return false
}

// SetEncrypted gets a reference to the given bool and assigns it to the Encrypted field.
func (o *FlyMachineMount) SetEncrypted(v bool) {
	o.Encrypted = &v
}

// GetExtendThresholdPercent returns the ExtendThresholdPercent field value if set, zero value otherwise.
func (o *FlyMachineMount) GetExtendThresholdPercent() int32 {
	if o == nil || IsNil(o.ExtendThresholdPercent) {
		var ret int32
		return ret
	}
	return *o.ExtendThresholdPercent
}

// GetExtendThresholdPercentOk returns a tuple with the ExtendThresholdPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyMachineMount) GetExtendThresholdPercentOk() (*int32, bool) {
	if o == nil || IsNil(o.ExtendThresholdPercent) {
		return nil, false
	}
	return o.ExtendThresholdPercent, true
}

// HasExtendThresholdPercent returns a boolean if a field has been set.
func (o *FlyMachineMount) HasExtendThresholdPercent() bool {
	if o != nil && !IsNil(o.ExtendThresholdPercent) {
		return true
	}

	return false
}

// SetExtendThresholdPercent gets a reference to the given int32 and assigns it to the ExtendThresholdPercent field.
func (o *FlyMachineMount) SetExtendThresholdPercent(v int32) {
	o.ExtendThresholdPercent = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FlyMachineMount) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyMachineMount) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FlyMachineMount) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FlyMachineMount) SetName(v string) {
	o.Name = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *FlyMachineMount) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyMachineMount) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *FlyMachineMount) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *FlyMachineMount) SetPath(v string) {
	o.Path = &v
}

// GetSizeGb returns the SizeGb field value if set, zero value otherwise.
func (o *FlyMachineMount) GetSizeGb() int32 {
	if o == nil || IsNil(o.SizeGb) {
		var ret int32
		return ret
	}
	return *o.SizeGb
}

// GetSizeGbOk returns a tuple with the SizeGb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyMachineMount) GetSizeGbOk() (*int32, bool) {
	if o == nil || IsNil(o.SizeGb) {
		return nil, false
	}
	return o.SizeGb, true
}

// HasSizeGb returns a boolean if a field has been set.
func (o *FlyMachineMount) HasSizeGb() bool {
	if o != nil && !IsNil(o.SizeGb) {
		return true
	}

	return false
}

// SetSizeGb gets a reference to the given int32 and assigns it to the SizeGb field.
func (o *FlyMachineMount) SetSizeGb(v int32) {
	o.SizeGb = &v
}

// GetSizeGbLimit returns the SizeGbLimit field value if set, zero value otherwise.
func (o *FlyMachineMount) GetSizeGbLimit() int32 {
	if o == nil || IsNil(o.SizeGbLimit) {
		var ret int32
		return ret
	}
	return *o.SizeGbLimit
}

// GetSizeGbLimitOk returns a tuple with the SizeGbLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyMachineMount) GetSizeGbLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.SizeGbLimit) {
		return nil, false
	}
	return o.SizeGbLimit, true
}

// HasSizeGbLimit returns a boolean if a field has been set.
func (o *FlyMachineMount) HasSizeGbLimit() bool {
	if o != nil && !IsNil(o.SizeGbLimit) {
		return true
	}

	return false
}

// SetSizeGbLimit gets a reference to the given int32 and assigns it to the SizeGbLimit field.
func (o *FlyMachineMount) SetSizeGbLimit(v int32) {
	o.SizeGbLimit = &v
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *FlyMachineMount) GetVolume() string {
	if o == nil || IsNil(o.Volume) {
		var ret string
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyMachineMount) GetVolumeOk() (*string, bool) {
	if o == nil || IsNil(o.Volume) {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *FlyMachineMount) HasVolume() bool {
	if o != nil && !IsNil(o.Volume) {
		return true
	}

	return false
}

// SetVolume gets a reference to the given string and assigns it to the Volume field.
func (o *FlyMachineMount) SetVolume(v string) {
	o.Volume = &v
}

func (o FlyMachineMount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlyMachineMount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddSizeGb) {
		toSerialize["add_size_gb"] = o.AddSizeGb
	}
	if !IsNil(o.Encrypted) {
		toSerialize["encrypted"] = o.Encrypted
	}
	if !IsNil(o.ExtendThresholdPercent) {
		toSerialize["extend_threshold_percent"] = o.ExtendThresholdPercent
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.SizeGb) {
		toSerialize["size_gb"] = o.SizeGb
	}
	if !IsNil(o.SizeGbLimit) {
		toSerialize["size_gb_limit"] = o.SizeGbLimit
	}
	if !IsNil(o.Volume) {
		toSerialize["volume"] = o.Volume
	}
	return toSerialize, nil
}

type NullableFlyMachineMount struct {
	value *FlyMachineMount
	isSet bool
}

func (v NullableFlyMachineMount) Get() *FlyMachineMount {
	return v.value
}

func (v *NullableFlyMachineMount) Set(val *FlyMachineMount) {
	v.value = val
	v.isSet = true
}

func (v NullableFlyMachineMount) IsSet() bool {
	return v.isSet
}

func (v *NullableFlyMachineMount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlyMachineMount(val *FlyMachineMount) *NullableFlyMachineMount {
	return &NullableFlyMachineMount{value: val, isSet: true}
}

func (v NullableFlyMachineMount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlyMachineMount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


