/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the SecretKeys type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretKeys{}

// SecretKeys struct for SecretKeys
type SecretKeys struct {
	SecretKeys []SecretKey `json:"secret_keys,omitempty"`
}

// NewSecretKeys instantiates a new SecretKeys object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretKeys() *SecretKeys {
	this := SecretKeys{}
	return &this
}

// NewSecretKeysWithDefaults instantiates a new SecretKeys object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretKeysWithDefaults() *SecretKeys {
	this := SecretKeys{}
	return &this
}

// GetSecretKeys returns the SecretKeys field value if set, zero value otherwise.
func (o *SecretKeys) GetSecretKeys() []SecretKey {
	if o == nil || IsNil(o.SecretKeys) {
		var ret []SecretKey
		return ret
	}
	return o.SecretKeys
}

// GetSecretKeysOk returns a tuple with the SecretKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretKeys) GetSecretKeysOk() ([]SecretKey, bool) {
	if o == nil || IsNil(o.SecretKeys) {
		return nil, false
	}
	return o.SecretKeys, true
}

// HasSecretKeys returns a boolean if a field has been set.
func (o *SecretKeys) HasSecretKeys() bool {
	if o != nil && !IsNil(o.SecretKeys) {
		return true
	}

	return false
}

// SetSecretKeys gets a reference to the given []SecretKey and assigns it to the SecretKeys field.
func (o *SecretKeys) SetSecretKeys(v []SecretKey) {
	o.SecretKeys = v
}

func (o SecretKeys) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretKeys) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SecretKeys) {
		toSerialize["secret_keys"] = o.SecretKeys
	}
	return toSerialize, nil
}

type NullableSecretKeys struct {
	value *SecretKeys
	isSet bool
}

func (v NullableSecretKeys) Get() *SecretKeys {
	return v.value
}

func (v *NullableSecretKeys) Set(val *SecretKeys) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretKeys) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretKeys) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretKeys(val *SecretKeys) *NullableSecretKeys {
	return &NullableSecretKeys{value: val, isSet: true}
}

func (v NullableSecretKeys) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretKeys) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


