/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the FlyMachineHTTPHeader type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlyMachineHTTPHeader{}

// FlyMachineHTTPHeader For http checks, an array of objects with string field Name and array of strings field Values. The key/value pairs specify header and header values that will get passed with the check call.
type FlyMachineHTTPHeader struct {
	// The header name
	Name *string `json:"name,omitempty"`
	// The header value
	Values []string `json:"values,omitempty"`
}

// NewFlyMachineHTTPHeader instantiates a new FlyMachineHTTPHeader object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlyMachineHTTPHeader() *FlyMachineHTTPHeader {
	this := FlyMachineHTTPHeader{}
	return &this
}

// NewFlyMachineHTTPHeaderWithDefaults instantiates a new FlyMachineHTTPHeader object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlyMachineHTTPHeaderWithDefaults() *FlyMachineHTTPHeader {
	this := FlyMachineHTTPHeader{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FlyMachineHTTPHeader) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyMachineHTTPHeader) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FlyMachineHTTPHeader) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FlyMachineHTTPHeader) SetName(v string) {
	o.Name = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *FlyMachineHTTPHeader) GetValues() []string {
	if o == nil || IsNil(o.Values) {
		var ret []string
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyMachineHTTPHeader) GetValuesOk() ([]string, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *FlyMachineHTTPHeader) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []string and assigns it to the Values field.
func (o *FlyMachineHTTPHeader) SetValues(v []string) {
	o.Values = v
}

func (o FlyMachineHTTPHeader) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlyMachineHTTPHeader) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	return toSerialize, nil
}

type NullableFlyMachineHTTPHeader struct {
	value *FlyMachineHTTPHeader
	isSet bool
}

func (v NullableFlyMachineHTTPHeader) Get() *FlyMachineHTTPHeader {
	return v.value
}

func (v *NullableFlyMachineHTTPHeader) Set(val *FlyMachineHTTPHeader) {
	v.value = val
	v.isSet = true
}

func (v NullableFlyMachineHTTPHeader) IsSet() bool {
	return v.isSet
}

func (v *NullableFlyMachineHTTPHeader) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlyMachineHTTPHeader(val *FlyMachineHTTPHeader) *NullableFlyMachineHTTPHeader {
	return &NullableFlyMachineHTTPHeader{value: val, isSet: true}
}

func (v NullableFlyMachineHTTPHeader) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlyMachineHTTPHeader) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


