/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
	"fmt"
)

// FlyContainerHealthcheckKind the model 'FlyContainerHealthcheckKind'
type FlyContainerHealthcheckKind string

// List of fly.ContainerHealthcheckKind
const (
	Readiness FlyContainerHealthcheckKind = "readiness"
	Liveness FlyContainerHealthcheckKind = "liveness"
)

// All allowed values of FlyContainerHealthcheckKind enum
var AllowedFlyContainerHealthcheckKindEnumValues = []FlyContainerHealthcheckKind{
	"readiness",
	"liveness",
}

func (v *FlyContainerHealthcheckKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FlyContainerHealthcheckKind(value)
	for _, existing := range AllowedFlyContainerHealthcheckKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FlyContainerHealthcheckKind", value)
}

// NewFlyContainerHealthcheckKindFromValue returns a pointer to a valid FlyContainerHealthcheckKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFlyContainerHealthcheckKindFromValue(v string) (*FlyContainerHealthcheckKind, error) {
	ev := FlyContainerHealthcheckKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FlyContainerHealthcheckKind: valid values are %v", v, AllowedFlyContainerHealthcheckKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FlyContainerHealthcheckKind) IsValid() bool {
	for _, existing := range AllowedFlyContainerHealthcheckKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to fly.ContainerHealthcheckKind value
func (v FlyContainerHealthcheckKind) Ptr() *FlyContainerHealthcheckKind {
	return &v
}

type NullableFlyContainerHealthcheckKind struct {
	value *FlyContainerHealthcheckKind
	isSet bool
}

func (v NullableFlyContainerHealthcheckKind) Get() *FlyContainerHealthcheckKind {
	return v.value
}

func (v *NullableFlyContainerHealthcheckKind) Set(val *FlyContainerHealthcheckKind) {
	v.value = val
	v.isSet = true
}

func (v NullableFlyContainerHealthcheckKind) IsSet() bool {
	return v.isSet
}

func (v *NullableFlyContainerHealthcheckKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlyContainerHealthcheckKind(val *FlyContainerHealthcheckKind) *NullableFlyContainerHealthcheckKind {
	return &NullableFlyContainerHealthcheckKind{value: val, isSet: true}
}

func (v NullableFlyContainerHealthcheckKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlyContainerHealthcheckKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

