/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the SecretKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretKey{}

// SecretKey struct for SecretKey
type SecretKey struct {
	Name *string `json:"name,omitempty"`
	PublicKey []int32 `json:"public_key,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewSecretKey instantiates a new SecretKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretKey() *SecretKey {
	this := SecretKey{}
	return &this
}

// NewSecretKeyWithDefaults instantiates a new SecretKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretKeyWithDefaults() *SecretKey {
	this := SecretKey{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SecretKey) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretKey) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SecretKey) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SecretKey) SetName(v string) {
	o.Name = &v
}

// GetPublicKey returns the PublicKey field value if set, zero value otherwise.
func (o *SecretKey) GetPublicKey() []int32 {
	if o == nil || IsNil(o.PublicKey) {
		var ret []int32
		return ret
	}
	return o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretKey) GetPublicKeyOk() ([]int32, bool) {
	if o == nil || IsNil(o.PublicKey) {
		return nil, false
	}
	return o.PublicKey, true
}

// HasPublicKey returns a boolean if a field has been set.
func (o *SecretKey) HasPublicKey() bool {
	if o != nil && !IsNil(o.PublicKey) {
		return true
	}

	return false
}

// SetPublicKey gets a reference to the given []int32 and assigns it to the PublicKey field.
func (o *SecretKey) SetPublicKey(v []int32) {
	o.PublicKey = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SecretKey) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretKey) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SecretKey) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SecretKey) SetType(v string) {
	o.Type = &v
}

func (o SecretKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PublicKey) {
		toSerialize["public_key"] = o.PublicKey
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableSecretKey struct {
	value *SecretKey
	isSet bool
}

func (v NullableSecretKey) Get() *SecretKey {
	return v.value
}

func (v *NullableSecretKey) Set(val *SecretKey) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretKey) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretKey(val *SecretKey) *NullableSecretKey {
	return &NullableSecretKey{value: val, isSet: true}
}

func (v NullableSecretKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


