/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the CreateSecretRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSecretRequest{}

// CreateSecretRequest struct for CreateSecretRequest
type CreateSecretRequest struct {
	Value []int32 `json:"value,omitempty"`
}

// NewCreateSecretRequest instantiates a new CreateSecretRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSecretRequest() *CreateSecretRequest {
	this := CreateSecretRequest{}
	return &this
}

// NewCreateSecretRequestWithDefaults instantiates a new CreateSecretRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSecretRequestWithDefaults() *CreateSecretRequest {
	this := CreateSecretRequest{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CreateSecretRequest) GetValue() []int32 {
	if o == nil || IsNil(o.Value) {
		var ret []int32
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSecretRequest) GetValueOk() ([]int32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CreateSecretRequest) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given []int32 and assigns it to the Value field.
func (o *CreateSecretRequest) SetValue(v []int32) {
	o.Value = v
}

func (o CreateSecretRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSecretRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableCreateSecretRequest struct {
	value *CreateSecretRequest
	isSet bool
}

func (v NullableCreateSecretRequest) Get() *CreateSecretRequest {
	return v.value
}

func (v *NullableCreateSecretRequest) Set(val *CreateSecretRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSecretRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSecretRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSecretRequest(val *CreateSecretRequest) *NullableCreateSecretRequest {
	return &NullableCreateSecretRequest{value: val, isSet: true}
}

func (v NullableCreateSecretRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSecretRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


