/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the MainGetPlacementsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MainGetPlacementsResponse{}

// MainGetPlacementsResponse struct for MainGetPlacementsResponse
type MainGetPlacementsResponse struct {
	Regions []PlacementRegionPlacement `json:"regions,omitempty"`
}

// NewMainGetPlacementsResponse instantiates a new MainGetPlacementsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMainGetPlacementsResponse() *MainGetPlacementsResponse {
	this := MainGetPlacementsResponse{}
	return &this
}

// NewMainGetPlacementsResponseWithDefaults instantiates a new MainGetPlacementsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMainGetPlacementsResponseWithDefaults() *MainGetPlacementsResponse {
	this := MainGetPlacementsResponse{}
	return &this
}

// GetRegions returns the Regions field value if set, zero value otherwise.
func (o *MainGetPlacementsResponse) GetRegions() []PlacementRegionPlacement {
	if o == nil || IsNil(o.Regions) {
		var ret []PlacementRegionPlacement
		return ret
	}
	return o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainGetPlacementsResponse) GetRegionsOk() ([]PlacementRegionPlacement, bool) {
	if o == nil || IsNil(o.Regions) {
		return nil, false
	}
	return o.Regions, true
}

// HasRegions returns a boolean if a field has been set.
func (o *MainGetPlacementsResponse) HasRegions() bool {
	if o != nil && !IsNil(o.Regions) {
		return true
	}

	return false
}

// SetRegions gets a reference to the given []PlacementRegionPlacement and assigns it to the Regions field.
func (o *MainGetPlacementsResponse) SetRegions(v []PlacementRegionPlacement) {
	o.Regions = v
}

func (o MainGetPlacementsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MainGetPlacementsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Regions) {
		toSerialize["regions"] = o.Regions
	}
	return toSerialize, nil
}

type NullableMainGetPlacementsResponse struct {
	value *MainGetPlacementsResponse
	isSet bool
}

func (v NullableMainGetPlacementsResponse) Get() *MainGetPlacementsResponse {
	return v.value
}

func (v *NullableMainGetPlacementsResponse) Set(val *MainGetPlacementsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMainGetPlacementsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMainGetPlacementsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMainGetPlacementsResponse(val *MainGetPlacementsResponse) *NullableMainGetPlacementsResponse {
	return &NullableMainGetPlacementsResponse{value: val, isSet: true}
}

func (v NullableMainGetPlacementsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMainGetPlacementsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


