/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the CreateOIDCTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOIDCTokenRequest{}

// CreateOIDCTokenRequest Optional parameters
type CreateOIDCTokenRequest struct {
	Aud *string `json:"aud,omitempty"`
}

// NewCreateOIDCTokenRequest instantiates a new CreateOIDCTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOIDCTokenRequest() *CreateOIDCTokenRequest {
	this := CreateOIDCTokenRequest{}
	return &this
}

// NewCreateOIDCTokenRequestWithDefaults instantiates a new CreateOIDCTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOIDCTokenRequestWithDefaults() *CreateOIDCTokenRequest {
	this := CreateOIDCTokenRequest{}
	return &this
}

// GetAud returns the Aud field value if set, zero value otherwise.
func (o *CreateOIDCTokenRequest) GetAud() string {
	if o == nil || IsNil(o.Aud) {
		var ret string
		return ret
	}
	return *o.Aud
}

// GetAudOk returns a tuple with the Aud field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOIDCTokenRequest) GetAudOk() (*string, bool) {
	if o == nil || IsNil(o.Aud) {
		return nil, false
	}
	return o.Aud, true
}

// HasAud returns a boolean if a field has been set.
func (o *CreateOIDCTokenRequest) HasAud() bool {
	if o != nil && !IsNil(o.Aud) {
		return true
	}

	return false
}

// SetAud gets a reference to the given string and assigns it to the Aud field.
func (o *CreateOIDCTokenRequest) SetAud(v string) {
	o.Aud = &v
}

func (o CreateOIDCTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOIDCTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Aud) {
		toSerialize["aud"] = o.Aud
	}
	return toSerialize, nil
}

type NullableCreateOIDCTokenRequest struct {
	value *CreateOIDCTokenRequest
	isSet bool
}

func (v NullableCreateOIDCTokenRequest) Get() *CreateOIDCTokenRequest {
	return v.value
}

func (v *NullableCreateOIDCTokenRequest) Set(val *CreateOIDCTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOIDCTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOIDCTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOIDCTokenRequest(val *CreateOIDCTokenRequest) *NullableCreateOIDCTokenRequest {
	return &NullableCreateOIDCTokenRequest{value: val, isSet: true}
}

func (v NullableCreateOIDCTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOIDCTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


