/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
	"fmt"
)

// FlyContainerHealthcheckScheme the model 'FlyContainerHealthcheckScheme'
type FlyContainerHealthcheckScheme string

// List of fly.ContainerHealthcheckScheme
const (
	HTTP FlyContainerHealthcheckScheme = "http"
	HTTPS FlyContainerHealthcheckScheme = "https"
)

// All allowed values of FlyContainerHealthcheckScheme enum
var AllowedFlyContainerHealthcheckSchemeEnumValues = []FlyContainerHealthcheckScheme{
	"http",
	"https",
}

func (v *FlyContainerHealthcheckScheme) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FlyContainerHealthcheckScheme(value)
	for _, existing := range AllowedFlyContainerHealthcheckSchemeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FlyContainerHealthcheckScheme", value)
}

// NewFlyContainerHealthcheckSchemeFromValue returns a pointer to a valid FlyContainerHealthcheckScheme
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFlyContainerHealthcheckSchemeFromValue(v string) (*FlyContainerHealthcheckScheme, error) {
	ev := FlyContainerHealthcheckScheme(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FlyContainerHealthcheckScheme: valid values are %v", v, AllowedFlyContainerHealthcheckSchemeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FlyContainerHealthcheckScheme) IsValid() bool {
	for _, existing := range AllowedFlyContainerHealthcheckSchemeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to fly.ContainerHealthcheckScheme value
func (v FlyContainerHealthcheckScheme) Ptr() *FlyContainerHealthcheckScheme {
	return &v
}

type NullableFlyContainerHealthcheckScheme struct {
	value *FlyContainerHealthcheckScheme
	isSet bool
}

func (v NullableFlyContainerHealthcheckScheme) Get() *FlyContainerHealthcheckScheme {
	return v.value
}

func (v *NullableFlyContainerHealthcheckScheme) Set(val *FlyContainerHealthcheckScheme) {
	v.value = val
	v.isSet = true
}

func (v NullableFlyContainerHealthcheckScheme) IsSet() bool {
	return v.isSet
}

func (v *NullableFlyContainerHealthcheckScheme) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlyContainerHealthcheckScheme(val *FlyContainerHealthcheckScheme) *NullableFlyContainerHealthcheckScheme {
	return &NullableFlyContainerHealthcheckScheme{value: val, isSet: true}
}

func (v NullableFlyContainerHealthcheckScheme) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlyContainerHealthcheckScheme) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

