/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the AppSecrets type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppSecrets{}

// AppSecrets struct for AppSecrets
type AppSecrets struct {
	Secrets []AppSecret `json:"secrets,omitempty"`
}

// NewAppSecrets instantiates a new AppSecrets object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppSecrets() *AppSecrets {
	this := AppSecrets{}
	return &this
}

// NewAppSecretsWithDefaults instantiates a new AppSecrets object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppSecretsWithDefaults() *AppSecrets {
	this := AppSecrets{}
	return &this
}

// GetSecrets returns the Secrets field value if set, zero value otherwise.
func (o *AppSecrets) GetSecrets() []AppSecret {
	if o == nil || IsNil(o.Secrets) {
		var ret []AppSecret
		return ret
	}
	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppSecrets) GetSecretsOk() ([]AppSecret, bool) {
	if o == nil || IsNil(o.Secrets) {
		return nil, false
	}
	return o.Secrets, true
}

// HasSecrets returns a boolean if a field has been set.
func (o *AppSecrets) HasSecrets() bool {
	if o != nil && !IsNil(o.Secrets) {
		return true
	}

	return false
}

// SetSecrets gets a reference to the given []AppSecret and assigns it to the Secrets field.
func (o *AppSecrets) SetSecrets(v []AppSecret) {
	o.Secrets = v
}

func (o AppSecrets) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppSecrets) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Secrets) {
		toSerialize["secrets"] = o.Secrets
	}
	return toSerialize, nil
}

type NullableAppSecrets struct {
	value *AppSecrets
	isSet bool
}

func (v NullableAppSecrets) Get() *AppSecrets {
	return v.value
}

func (v *NullableAppSecrets) Set(val *AppSecrets) {
	v.value = val
	v.isSet = true
}

func (v NullableAppSecrets) IsSet() bool {
	return v.isSet
}

func (v *NullableAppSecrets) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppSecrets(val *AppSecrets) *NullableAppSecrets {
	return &NullableAppSecrets{value: val, isSet: true}
}

func (v NullableAppSecrets) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppSecrets) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


