/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the FlyExecHealthcheck type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlyExecHealthcheck{}

// FlyExecHealthcheck struct for FlyExecHealthcheck
type FlyExecHealthcheck struct {
	// The command to run to check the health of the container (e.g. [\"cat\", \"/tmp/healthy\"])
	Command []string `json:"command,omitempty"`
}

// NewFlyExecHealthcheck instantiates a new FlyExecHealthcheck object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlyExecHealthcheck() *FlyExecHealthcheck {
	this := FlyExecHealthcheck{}
	return &this
}

// NewFlyExecHealthcheckWithDefaults instantiates a new FlyExecHealthcheck object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlyExecHealthcheckWithDefaults() *FlyExecHealthcheck {
	this := FlyExecHealthcheck{}
	return &this
}

// GetCommand returns the Command field value if set, zero value otherwise.
func (o *FlyExecHealthcheck) GetCommand() []string {
	if o == nil || IsNil(o.Command) {
		var ret []string
		return ret
	}
	return o.Command
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyExecHealthcheck) GetCommandOk() ([]string, bool) {
	if o == nil || IsNil(o.Command) {
		return nil, false
	}
	return o.Command, true
}

// HasCommand returns a boolean if a field has been set.
func (o *FlyExecHealthcheck) HasCommand() bool {
	if o != nil && !IsNil(o.Command) {
		return true
	}

	return false
}

// SetCommand gets a reference to the given []string and assigns it to the Command field.
func (o *FlyExecHealthcheck) SetCommand(v []string) {
	o.Command = v
}

func (o FlyExecHealthcheck) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlyExecHealthcheck) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Command) {
		toSerialize["command"] = o.Command
	}
	return toSerialize, nil
}

type NullableFlyExecHealthcheck struct {
	value *FlyExecHealthcheck
	isSet bool
}

func (v NullableFlyExecHealthcheck) Get() *FlyExecHealthcheck {
	return v.value
}

func (v *NullableFlyExecHealthcheck) Set(val *FlyExecHealthcheck) {
	v.value = val
	v.isSet = true
}

func (v NullableFlyExecHealthcheck) IsSet() bool {
	return v.isSet
}

func (v *NullableFlyExecHealthcheck) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlyExecHealthcheck(val *FlyExecHealthcheck) *NullableFlyExecHealthcheck {
	return &NullableFlyExecHealthcheck{value: val, isSet: true}
}

func (v NullableFlyExecHealthcheck) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlyExecHealthcheck) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


