/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the FlyTCPHealthcheck type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlyTCPHealthcheck{}

// FlyTCPHealthcheck struct for FlyTCPHealthcheck
type FlyTCPHealthcheck struct {
	// The port to connect to, often the same as internal_port
	Port *int32 `json:"port,omitempty"`
}

// NewFlyTCPHealthcheck instantiates a new FlyTCPHealthcheck object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlyTCPHealthcheck() *FlyTCPHealthcheck {
	this := FlyTCPHealthcheck{}
	return &this
}

// NewFlyTCPHealthcheckWithDefaults instantiates a new FlyTCPHealthcheck object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlyTCPHealthcheckWithDefaults() *FlyTCPHealthcheck {
	this := FlyTCPHealthcheck{}
	return &this
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *FlyTCPHealthcheck) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyTCPHealthcheck) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *FlyTCPHealthcheck) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *FlyTCPHealthcheck) SetPort(v int32) {
	o.Port = &v
}

func (o FlyTCPHealthcheck) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlyTCPHealthcheck) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	return toSerialize, nil
}

type NullableFlyTCPHealthcheck struct {
	value *FlyTCPHealthcheck
	isSet bool
}

func (v NullableFlyTCPHealthcheck) Get() *FlyTCPHealthcheck {
	return v.value
}

func (v *NullableFlyTCPHealthcheck) Set(val *FlyTCPHealthcheck) {
	v.value = val
	v.isSet = true
}

func (v NullableFlyTCPHealthcheck) IsSet() bool {
	return v.isSet
}

func (v *NullableFlyTCPHealthcheck) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlyTCPHealthcheck(val *FlyTCPHealthcheck) *NullableFlyTCPHealthcheck {
	return &NullableFlyTCPHealthcheck{value: val, isSet: true}
}

func (v NullableFlyTCPHealthcheck) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlyTCPHealthcheck) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


