/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the VerifySecretkeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifySecretkeyRequest{}

// VerifySecretkeyRequest struct for VerifySecretkeyRequest
type VerifySecretkeyRequest struct {
	Plaintext []int32 `json:"plaintext,omitempty"`
	Signature []int32 `json:"signature,omitempty"`
}

// NewVerifySecretkeyRequest instantiates a new VerifySecretkeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifySecretkeyRequest() *VerifySecretkeyRequest {
	this := VerifySecretkeyRequest{}
	return &this
}

// NewVerifySecretkeyRequestWithDefaults instantiates a new VerifySecretkeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifySecretkeyRequestWithDefaults() *VerifySecretkeyRequest {
	this := VerifySecretkeyRequest{}
	return &this
}

// GetPlaintext returns the Plaintext field value if set, zero value otherwise.
func (o *VerifySecretkeyRequest) GetPlaintext() []int32 {
	if o == nil || IsNil(o.Plaintext) {
		var ret []int32
		return ret
	}
	return o.Plaintext
}

// GetPlaintextOk returns a tuple with the Plaintext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySecretkeyRequest) GetPlaintextOk() ([]int32, bool) {
	if o == nil || IsNil(o.Plaintext) {
		return nil, false
	}
	return o.Plaintext, true
}

// HasPlaintext returns a boolean if a field has been set.
func (o *VerifySecretkeyRequest) HasPlaintext() bool {
	if o != nil && !IsNil(o.Plaintext) {
		return true
	}

	return false
}

// SetPlaintext gets a reference to the given []int32 and assigns it to the Plaintext field.
func (o *VerifySecretkeyRequest) SetPlaintext(v []int32) {
	o.Plaintext = v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *VerifySecretkeyRequest) GetSignature() []int32 {
	if o == nil || IsNil(o.Signature) {
		var ret []int32
		return ret
	}
	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySecretkeyRequest) GetSignatureOk() ([]int32, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *VerifySecretkeyRequest) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given []int32 and assigns it to the Signature field.
func (o *VerifySecretkeyRequest) SetSignature(v []int32) {
	o.Signature = v
}

func (o VerifySecretkeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifySecretkeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Plaintext) {
		toSerialize["plaintext"] = o.Plaintext
	}
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	return toSerialize, nil
}

type NullableVerifySecretkeyRequest struct {
	value *VerifySecretkeyRequest
	isSet bool
}

func (v NullableVerifySecretkeyRequest) Get() *VerifySecretkeyRequest {
	return v.value
}

func (v *NullableVerifySecretkeyRequest) Set(val *VerifySecretkeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifySecretkeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifySecretkeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifySecretkeyRequest(val *VerifySecretkeyRequest) *NullableVerifySecretkeyRequest {
	return &NullableVerifySecretkeyRequest{value: val, isSet: true}
}

func (v NullableVerifySecretkeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifySecretkeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


