/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the FlyContainerConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlyContainerConfig{}

// FlyContainerConfig struct for FlyContainerConfig
type FlyContainerConfig struct {
	// CmdOverride is used to override the default command of the image.
	Cmd []string `json:"cmd,omitempty"`
	// DependsOn can be used to define dependencies between containers. The container will only be started after all of its dependent conditions have been satisfied.
	DependsOn []FlyContainerDependency `json:"depends_on,omitempty"`
	// EntrypointOverride is used to override the default entrypoint of the image.
	Entrypoint []string `json:"entrypoint,omitempty"`
	// ExtraEnv is used to add additional environment variables to the container.
	Env *map[string]string `json:"env,omitempty"`
	// EnvFrom can be provided to set environment variables from machine fields.
	EnvFrom []FlyEnvFrom `json:"env_from,omitempty"`
	// Image Config overrides - these fields are used to override the image configuration. If not provided, the image configuration will be used. ExecOverride is used to override the default command of the image.
	Exec []string `json:"exec,omitempty"`
	// Files are files that will be written to the container file system.
	Files []FlyFile `json:"files,omitempty"`
	// Healthchecks determine the health of your containers. Healthchecks can use HTTP, TCP or an Exec command.
	Healthchecks []FlyContainerHealthcheck `json:"healthchecks,omitempty"`
	// Image is the docker image to run.
	Image *string `json:"image,omitempty"`
	// Name is used to identify the container in the machine.
	Name *string `json:"name,omitempty"`
	// Restart is used to define the restart policy for the container. NOTE: spot-price is not supported for containers.
	Restart *FlyMachineRestart `json:"restart,omitempty"`
	// Secrets can be provided at the process level to explicitly indicate which secrets should be used for the process. If not provided, the secrets provided at the machine level will be used.
	Secrets []FlyMachineSecret `json:"secrets,omitempty"`
	// Stop is used to define the signal and timeout for stopping the container.
	Stop *FlyStopConfig `json:"stop,omitempty"`
	// UserOverride is used to override the default user of the image.
	User *string `json:"user,omitempty"`
}

// NewFlyContainerConfig instantiates a new FlyContainerConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlyContainerConfig() *FlyContainerConfig {
	this := FlyContainerConfig{}
	return &this
}

// NewFlyContainerConfigWithDefaults instantiates a new FlyContainerConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlyContainerConfigWithDefaults() *FlyContainerConfig {
	this := FlyContainerConfig{}
	return &this
}

// GetCmd returns the Cmd field value if set, zero value otherwise.
func (o *FlyContainerConfig) GetCmd() []string {
	if o == nil || IsNil(o.Cmd) {
		var ret []string
		return ret
	}
	return o.Cmd
}

// GetCmdOk returns a tuple with the Cmd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerConfig) GetCmdOk() ([]string, bool) {
	if o == nil || IsNil(o.Cmd) {
		return nil, false
	}
	return o.Cmd, true
}

// HasCmd returns a boolean if a field has been set.
func (o *FlyContainerConfig) HasCmd() bool {
	if o != nil && !IsNil(o.Cmd) {
		return true
	}

	return false
}

// SetCmd gets a reference to the given []string and assigns it to the Cmd field.
func (o *FlyContainerConfig) SetCmd(v []string) {
	o.Cmd = v
}

// GetDependsOn returns the DependsOn field value if set, zero value otherwise.
func (o *FlyContainerConfig) GetDependsOn() []FlyContainerDependency {
	if o == nil || IsNil(o.DependsOn) {
		var ret []FlyContainerDependency
		return ret
	}
	return o.DependsOn
}

// GetDependsOnOk returns a tuple with the DependsOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerConfig) GetDependsOnOk() ([]FlyContainerDependency, bool) {
	if o == nil || IsNil(o.DependsOn) {
		return nil, false
	}
	return o.DependsOn, true
}

// HasDependsOn returns a boolean if a field has been set.
func (o *FlyContainerConfig) HasDependsOn() bool {
	if o != nil && !IsNil(o.DependsOn) {
		return true
	}

	return false
}

// SetDependsOn gets a reference to the given []FlyContainerDependency and assigns it to the DependsOn field.
func (o *FlyContainerConfig) SetDependsOn(v []FlyContainerDependency) {
	o.DependsOn = v
}

// GetEntrypoint returns the Entrypoint field value if set, zero value otherwise.
func (o *FlyContainerConfig) GetEntrypoint() []string {
	if o == nil || IsNil(o.Entrypoint) {
		var ret []string
		return ret
	}
	return o.Entrypoint
}

// GetEntrypointOk returns a tuple with the Entrypoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerConfig) GetEntrypointOk() ([]string, bool) {
	if o == nil || IsNil(o.Entrypoint) {
		return nil, false
	}
	return o.Entrypoint, true
}

// HasEntrypoint returns a boolean if a field has been set.
func (o *FlyContainerConfig) HasEntrypoint() bool {
	if o != nil && !IsNil(o.Entrypoint) {
		return true
	}

	return false
}

// SetEntrypoint gets a reference to the given []string and assigns it to the Entrypoint field.
func (o *FlyContainerConfig) SetEntrypoint(v []string) {
	o.Entrypoint = v
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *FlyContainerConfig) GetEnv() map[string]string {
	if o == nil || IsNil(o.Env) {
		var ret map[string]string
		return ret
	}
	return *o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerConfig) GetEnvOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *FlyContainerConfig) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given map[string]string and assigns it to the Env field.
func (o *FlyContainerConfig) SetEnv(v map[string]string) {
	o.Env = &v
}

// GetEnvFrom returns the EnvFrom field value if set, zero value otherwise.
func (o *FlyContainerConfig) GetEnvFrom() []FlyEnvFrom {
	if o == nil || IsNil(o.EnvFrom) {
		var ret []FlyEnvFrom
		return ret
	}
	return o.EnvFrom
}

// GetEnvFromOk returns a tuple with the EnvFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerConfig) GetEnvFromOk() ([]FlyEnvFrom, bool) {
	if o == nil || IsNil(o.EnvFrom) {
		return nil, false
	}
	return o.EnvFrom, true
}

// HasEnvFrom returns a boolean if a field has been set.
func (o *FlyContainerConfig) HasEnvFrom() bool {
	if o != nil && !IsNil(o.EnvFrom) {
		return true
	}

	return false
}

// SetEnvFrom gets a reference to the given []FlyEnvFrom and assigns it to the EnvFrom field.
func (o *FlyContainerConfig) SetEnvFrom(v []FlyEnvFrom) {
	o.EnvFrom = v
}

// GetExec returns the Exec field value if set, zero value otherwise.
func (o *FlyContainerConfig) GetExec() []string {
	if o == nil || IsNil(o.Exec) {
		var ret []string
		return ret
	}
	return o.Exec
}

// GetExecOk returns a tuple with the Exec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerConfig) GetExecOk() ([]string, bool) {
	if o == nil || IsNil(o.Exec) {
		return nil, false
	}
	return o.Exec, true
}

// HasExec returns a boolean if a field has been set.
func (o *FlyContainerConfig) HasExec() bool {
	if o != nil && !IsNil(o.Exec) {
		return true
	}

	return false
}

// SetExec gets a reference to the given []string and assigns it to the Exec field.
func (o *FlyContainerConfig) SetExec(v []string) {
	o.Exec = v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *FlyContainerConfig) GetFiles() []FlyFile {
	if o == nil || IsNil(o.Files) {
		var ret []FlyFile
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerConfig) GetFilesOk() ([]FlyFile, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *FlyContainerConfig) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []FlyFile and assigns it to the Files field.
func (o *FlyContainerConfig) SetFiles(v []FlyFile) {
	o.Files = v
}

// GetHealthchecks returns the Healthchecks field value if set, zero value otherwise.
func (o *FlyContainerConfig) GetHealthchecks() []FlyContainerHealthcheck {
	if o == nil || IsNil(o.Healthchecks) {
		var ret []FlyContainerHealthcheck
		return ret
	}
	return o.Healthchecks
}

// GetHealthchecksOk returns a tuple with the Healthchecks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerConfig) GetHealthchecksOk() ([]FlyContainerHealthcheck, bool) {
	if o == nil || IsNil(o.Healthchecks) {
		return nil, false
	}
	return o.Healthchecks, true
}

// HasHealthchecks returns a boolean if a field has been set.
func (o *FlyContainerConfig) HasHealthchecks() bool {
	if o != nil && !IsNil(o.Healthchecks) {
		return true
	}

	return false
}

// SetHealthchecks gets a reference to the given []FlyContainerHealthcheck and assigns it to the Healthchecks field.
func (o *FlyContainerConfig) SetHealthchecks(v []FlyContainerHealthcheck) {
	o.Healthchecks = v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *FlyContainerConfig) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerConfig) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *FlyContainerConfig) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *FlyContainerConfig) SetImage(v string) {
	o.Image = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FlyContainerConfig) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerConfig) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FlyContainerConfig) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FlyContainerConfig) SetName(v string) {
	o.Name = &v
}

// GetRestart returns the Restart field value if set, zero value otherwise.
func (o *FlyContainerConfig) GetRestart() FlyMachineRestart {
	if o == nil || IsNil(o.Restart) {
		var ret FlyMachineRestart
		return ret
	}
	return *o.Restart
}

// GetRestartOk returns a tuple with the Restart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerConfig) GetRestartOk() (*FlyMachineRestart, bool) {
	if o == nil || IsNil(o.Restart) {
		return nil, false
	}
	return o.Restart, true
}

// HasRestart returns a boolean if a field has been set.
func (o *FlyContainerConfig) HasRestart() bool {
	if o != nil && !IsNil(o.Restart) {
		return true
	}

	return false
}

// SetRestart gets a reference to the given FlyMachineRestart and assigns it to the Restart field.
func (o *FlyContainerConfig) SetRestart(v FlyMachineRestart) {
	o.Restart = &v
}

// GetSecrets returns the Secrets field value if set, zero value otherwise.
func (o *FlyContainerConfig) GetSecrets() []FlyMachineSecret {
	if o == nil || IsNil(o.Secrets) {
		var ret []FlyMachineSecret
		return ret
	}
	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerConfig) GetSecretsOk() ([]FlyMachineSecret, bool) {
	if o == nil || IsNil(o.Secrets) {
		return nil, false
	}
	return o.Secrets, true
}

// HasSecrets returns a boolean if a field has been set.
func (o *FlyContainerConfig) HasSecrets() bool {
	if o != nil && !IsNil(o.Secrets) {
		return true
	}

	return false
}

// SetSecrets gets a reference to the given []FlyMachineSecret and assigns it to the Secrets field.
func (o *FlyContainerConfig) SetSecrets(v []FlyMachineSecret) {
	o.Secrets = v
}

// GetStop returns the Stop field value if set, zero value otherwise.
func (o *FlyContainerConfig) GetStop() FlyStopConfig {
	if o == nil || IsNil(o.Stop) {
		var ret FlyStopConfig
		return ret
	}
	return *o.Stop
}

// GetStopOk returns a tuple with the Stop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerConfig) GetStopOk() (*FlyStopConfig, bool) {
	if o == nil || IsNil(o.Stop) {
		return nil, false
	}
	return o.Stop, true
}

// HasStop returns a boolean if a field has been set.
func (o *FlyContainerConfig) HasStop() bool {
	if o != nil && !IsNil(o.Stop) {
		return true
	}

	return false
}

// SetStop gets a reference to the given FlyStopConfig and assigns it to the Stop field.
func (o *FlyContainerConfig) SetStop(v FlyStopConfig) {
	o.Stop = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *FlyContainerConfig) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerConfig) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *FlyContainerConfig) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *FlyContainerConfig) SetUser(v string) {
	o.User = &v
}

func (o FlyContainerConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlyContainerConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cmd) {
		toSerialize["cmd"] = o.Cmd
	}
	if !IsNil(o.DependsOn) {
		toSerialize["depends_on"] = o.DependsOn
	}
	if !IsNil(o.Entrypoint) {
		toSerialize["entrypoint"] = o.Entrypoint
	}
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !IsNil(o.EnvFrom) {
		toSerialize["env_from"] = o.EnvFrom
	}
	if !IsNil(o.Exec) {
		toSerialize["exec"] = o.Exec
	}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	if !IsNil(o.Healthchecks) {
		toSerialize["healthchecks"] = o.Healthchecks
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Restart) {
		toSerialize["restart"] = o.Restart
	}
	if !IsNil(o.Secrets) {
		toSerialize["secrets"] = o.Secrets
	}
	if !IsNil(o.Stop) {
		toSerialize["stop"] = o.Stop
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullableFlyContainerConfig struct {
	value *FlyContainerConfig
	isSet bool
}

func (v NullableFlyContainerConfig) Get() *FlyContainerConfig {
	return v.value
}

func (v *NullableFlyContainerConfig) Set(val *FlyContainerConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableFlyContainerConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableFlyContainerConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlyContainerConfig(val *FlyContainerConfig) *NullableFlyContainerConfig {
	return &NullableFlyContainerConfig{value: val, isSet: true}
}

func (v NullableFlyContainerConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlyContainerConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


