/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the FlyContainerDependency type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlyContainerDependency{}

// FlyContainerDependency struct for FlyContainerDependency
type FlyContainerDependency struct {
	Condition *FlyContainerDependencyCondition `json:"condition,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewFlyContainerDependency instantiates a new FlyContainerDependency object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlyContainerDependency() *FlyContainerDependency {
	this := FlyContainerDependency{}
	return &this
}

// NewFlyContainerDependencyWithDefaults instantiates a new FlyContainerDependency object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlyContainerDependencyWithDefaults() *FlyContainerDependency {
	this := FlyContainerDependency{}
	return &this
}

// GetCondition returns the Condition field value if set, zero value otherwise.
func (o *FlyContainerDependency) GetCondition() FlyContainerDependencyCondition {
	if o == nil || IsNil(o.Condition) {
		var ret FlyContainerDependencyCondition
		return ret
	}
	return *o.Condition
}

// GetConditionOk returns a tuple with the Condition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerDependency) GetConditionOk() (*FlyContainerDependencyCondition, bool) {
	if o == nil || IsNil(o.Condition) {
		return nil, false
	}
	return o.Condition, true
}

// HasCondition returns a boolean if a field has been set.
func (o *FlyContainerDependency) HasCondition() bool {
	if o != nil && !IsNil(o.Condition) {
		return true
	}

	return false
}

// SetCondition gets a reference to the given FlyContainerDependencyCondition and assigns it to the Condition field.
func (o *FlyContainerDependency) SetCondition(v FlyContainerDependencyCondition) {
	o.Condition = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FlyContainerDependency) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyContainerDependency) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FlyContainerDependency) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FlyContainerDependency) SetName(v string) {
	o.Name = &v
}

func (o FlyContainerDependency) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlyContainerDependency) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Condition) {
		toSerialize["condition"] = o.Condition
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableFlyContainerDependency struct {
	value *FlyContainerDependency
	isSet bool
}

func (v NullableFlyContainerDependency) Get() *FlyContainerDependency {
	return v.value
}

func (v *NullableFlyContainerDependency) Set(val *FlyContainerDependency) {
	v.value = val
	v.isSet = true
}

func (v NullableFlyContainerDependency) IsSet() bool {
	return v.isSet
}

func (v *NullableFlyContainerDependency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlyContainerDependency(val *FlyContainerDependency) *NullableFlyContainerDependency {
	return &NullableFlyContainerDependency{value: val, isSet: true}
}

func (v NullableFlyContainerDependency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlyContainerDependency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


