/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the MainRegionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MainRegionResponse{}

// MainRegionResponse struct for MainRegionResponse
type MainRegionResponse struct {
	Regions []ReadsGetCapacityPerRegionRow `json:"regions,omitempty"`
}

// NewMainRegionResponse instantiates a new MainRegionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMainRegionResponse() *MainRegionResponse {
	this := MainRegionResponse{}
	return &this
}

// NewMainRegionResponseWithDefaults instantiates a new MainRegionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMainRegionResponseWithDefaults() *MainRegionResponse {
	this := MainRegionResponse{}
	return &this
}

// GetRegions returns the Regions field value if set, zero value otherwise.
func (o *MainRegionResponse) GetRegions() []ReadsGetCapacityPerRegionRow {
	if o == nil || IsNil(o.Regions) {
		var ret []ReadsGetCapacityPerRegionRow
		return ret
	}
	return o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainRegionResponse) GetRegionsOk() ([]ReadsGetCapacityPerRegionRow, bool) {
	if o == nil || IsNil(o.Regions) {
		return nil, false
	}
	return o.Regions, true
}

// HasRegions returns a boolean if a field has been set.
func (o *MainRegionResponse) HasRegions() bool {
	if o != nil && !IsNil(o.Regions) {
		return true
	}

	return false
}

// SetRegions gets a reference to the given []ReadsGetCapacityPerRegionRow and assigns it to the Regions field.
func (o *MainRegionResponse) SetRegions(v []ReadsGetCapacityPerRegionRow) {
	o.Regions = v
}

func (o MainRegionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MainRegionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Regions) {
		toSerialize["regions"] = o.Regions
	}
	return toSerialize, nil
}

type NullableMainRegionResponse struct {
	value *MainRegionResponse
	isSet bool
}

func (v NullableMainRegionResponse) Get() *MainRegionResponse {
	return v.value
}

func (v *NullableMainRegionResponse) Set(val *MainRegionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMainRegionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMainRegionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMainRegionResponse(val *MainRegionResponse) *NullableMainRegionResponse {
	return &NullableMainRegionResponse{value: val, isSet: true}
}

func (v NullableMainRegionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMainRegionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


