/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the SetAppSecretRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetAppSecretRequest{}

// SetAppSecretRequest struct for SetAppSecretRequest
type SetAppSecretRequest struct {
	Value *string `json:"value,omitempty"`
}

// NewSetAppSecretRequest instantiates a new SetAppSecretRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetAppSecretRequest() *SetAppSecretRequest {
	this := SetAppSecretRequest{}
	return &this
}

// NewSetAppSecretRequestWithDefaults instantiates a new SetAppSecretRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetAppSecretRequestWithDefaults() *SetAppSecretRequest {
	this := SetAppSecretRequest{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SetAppSecretRequest) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetAppSecretRequest) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SetAppSecretRequest) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *SetAppSecretRequest) SetValue(v string) {
	o.Value = &v
}

func (o SetAppSecretRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetAppSecretRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableSetAppSecretRequest struct {
	value *SetAppSecretRequest
	isSet bool
}

func (v NullableSetAppSecretRequest) Get() *SetAppSecretRequest {
	return v.value
}

func (v *NullableSetAppSecretRequest) Set(val *SetAppSecretRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetAppSecretRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetAppSecretRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetAppSecretRequest(val *SetAppSecretRequest) *NullableSetAppSecretRequest {
	return &NullableSetAppSecretRequest{value: val, isSet: true}
}

func (v NullableSetAppSecretRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetAppSecretRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


