/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the FlyDuration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlyDuration{}

// FlyDuration struct for FlyDuration
type FlyDuration struct {
	TimeDuration *int32 `json:"time.Duration,omitempty"`
}

// NewFlyDuration instantiates a new FlyDuration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlyDuration() *FlyDuration {
	this := FlyDuration{}
	return &this
}

// NewFlyDurationWithDefaults instantiates a new FlyDuration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlyDurationWithDefaults() *FlyDuration {
	this := FlyDuration{}
	return &this
}

// GetTimeDuration returns the TimeDuration field value if set, zero value otherwise.
func (o *FlyDuration) GetTimeDuration() int32 {
	if o == nil || IsNil(o.TimeDuration) {
		var ret int32
		return ret
	}
	return *o.TimeDuration
}

// GetTimeDurationOk returns a tuple with the TimeDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyDuration) GetTimeDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.TimeDuration) {
		return nil, false
	}
	return o.TimeDuration, true
}

// HasTimeDuration returns a boolean if a field has been set.
func (o *FlyDuration) HasTimeDuration() bool {
	if o != nil && !IsNil(o.TimeDuration) {
		return true
	}

	return false
}

// SetTimeDuration gets a reference to the given int32 and assigns it to the TimeDuration field.
func (o *FlyDuration) SetTimeDuration(v int32) {
	o.TimeDuration = &v
}

func (o FlyDuration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlyDuration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimeDuration) {
		toSerialize["time.Duration"] = o.TimeDuration
	}
	return toSerialize, nil
}

type NullableFlyDuration struct {
	value *FlyDuration
	isSet bool
}

func (v NullableFlyDuration) Get() *FlyDuration {
	return v.value
}

func (v *NullableFlyDuration) Set(val *FlyDuration) {
	v.value = val
	v.isSet = true
}

func (v NullableFlyDuration) IsSet() bool {
	return v.isSet
}

func (v *NullableFlyDuration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlyDuration(val *FlyDuration) *NullableFlyDuration {
	return &NullableFlyDuration{value: val, isSet: true}
}

func (v NullableFlyDuration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlyDuration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


