/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the FlyHTTPHealthcheck type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlyHTTPHealthcheck{}

// FlyHTTPHealthcheck struct for FlyHTTPHealthcheck
type FlyHTTPHealthcheck struct {
	// Additional headers to send with the request
	Headers []FlyMachineHTTPHeader `json:"headers,omitempty"`
	// The HTTP method to use to when making the request
	Method *string `json:"method,omitempty"`
	// The path to send the request to
	Path *string `json:"path,omitempty"`
	// The port to connect to, often the same as internal_port
	Port *int64 `json:"port,omitempty"`
	// Whether to use http or https
	Scheme *FlyContainerHealthcheckScheme `json:"scheme,omitempty"`
	// If the protocol is https, the hostname to use for TLS certificate validation
	TlsServerName *string `json:"tls_server_name,omitempty"`
	// If the protocol is https, whether or not to verify the TLS certificate
	TlsSkipVerify *bool `json:"tls_skip_verify,omitempty"`
}

// NewFlyHTTPHealthcheck instantiates a new FlyHTTPHealthcheck object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlyHTTPHealthcheck() *FlyHTTPHealthcheck {
	this := FlyHTTPHealthcheck{}
	return &this
}

// NewFlyHTTPHealthcheckWithDefaults instantiates a new FlyHTTPHealthcheck object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlyHTTPHealthcheckWithDefaults() *FlyHTTPHealthcheck {
	this := FlyHTTPHealthcheck{}
	return &this
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *FlyHTTPHealthcheck) GetHeaders() []FlyMachineHTTPHeader {
	if o == nil || IsNil(o.Headers) {
		var ret []FlyMachineHTTPHeader
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyHTTPHealthcheck) GetHeadersOk() ([]FlyMachineHTTPHeader, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *FlyHTTPHealthcheck) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given []FlyMachineHTTPHeader and assigns it to the Headers field.
func (o *FlyHTTPHealthcheck) SetHeaders(v []FlyMachineHTTPHeader) {
	o.Headers = v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *FlyHTTPHealthcheck) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyHTTPHealthcheck) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *FlyHTTPHealthcheck) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *FlyHTTPHealthcheck) SetMethod(v string) {
	o.Method = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *FlyHTTPHealthcheck) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyHTTPHealthcheck) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *FlyHTTPHealthcheck) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *FlyHTTPHealthcheck) SetPath(v string) {
	o.Path = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *FlyHTTPHealthcheck) GetPort() int64 {
	if o == nil || IsNil(o.Port) {
		var ret int64
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyHTTPHealthcheck) GetPortOk() (*int64, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *FlyHTTPHealthcheck) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int64 and assigns it to the Port field.
func (o *FlyHTTPHealthcheck) SetPort(v int64) {
	o.Port = &v
}

// GetScheme returns the Scheme field value if set, zero value otherwise.
func (o *FlyHTTPHealthcheck) GetScheme() FlyContainerHealthcheckScheme {
	if o == nil || IsNil(o.Scheme) {
		var ret FlyContainerHealthcheckScheme
		return ret
	}
	return *o.Scheme
}

// GetSchemeOk returns a tuple with the Scheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyHTTPHealthcheck) GetSchemeOk() (*FlyContainerHealthcheckScheme, bool) {
	if o == nil || IsNil(o.Scheme) {
		return nil, false
	}
	return o.Scheme, true
}

// HasScheme returns a boolean if a field has been set.
func (o *FlyHTTPHealthcheck) HasScheme() bool {
	if o != nil && !IsNil(o.Scheme) {
		return true
	}

	return false
}

// SetScheme gets a reference to the given FlyContainerHealthcheckScheme and assigns it to the Scheme field.
func (o *FlyHTTPHealthcheck) SetScheme(v FlyContainerHealthcheckScheme) {
	o.Scheme = &v
}

// GetTlsServerName returns the TlsServerName field value if set, zero value otherwise.
func (o *FlyHTTPHealthcheck) GetTlsServerName() string {
	if o == nil || IsNil(o.TlsServerName) {
		var ret string
		return ret
	}
	return *o.TlsServerName
}

// GetTlsServerNameOk returns a tuple with the TlsServerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyHTTPHealthcheck) GetTlsServerNameOk() (*string, bool) {
	if o == nil || IsNil(o.TlsServerName) {
		return nil, false
	}
	return o.TlsServerName, true
}

// HasTlsServerName returns a boolean if a field has been set.
func (o *FlyHTTPHealthcheck) HasTlsServerName() bool {
	if o != nil && !IsNil(o.TlsServerName) {
		return true
	}

	return false
}

// SetTlsServerName gets a reference to the given string and assigns it to the TlsServerName field.
func (o *FlyHTTPHealthcheck) SetTlsServerName(v string) {
	o.TlsServerName = &v
}

// GetTlsSkipVerify returns the TlsSkipVerify field value if set, zero value otherwise.
func (o *FlyHTTPHealthcheck) GetTlsSkipVerify() bool {
	if o == nil || IsNil(o.TlsSkipVerify) {
		var ret bool
		return ret
	}
	return *o.TlsSkipVerify
}

// GetTlsSkipVerifyOk returns a tuple with the TlsSkipVerify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyHTTPHealthcheck) GetTlsSkipVerifyOk() (*bool, bool) {
	if o == nil || IsNil(o.TlsSkipVerify) {
		return nil, false
	}
	return o.TlsSkipVerify, true
}

// HasTlsSkipVerify returns a boolean if a field has been set.
func (o *FlyHTTPHealthcheck) HasTlsSkipVerify() bool {
	if o != nil && !IsNil(o.TlsSkipVerify) {
		return true
	}

	return false
}

// SetTlsSkipVerify gets a reference to the given bool and assigns it to the TlsSkipVerify field.
func (o *FlyHTTPHealthcheck) SetTlsSkipVerify(v bool) {
	o.TlsSkipVerify = &v
}

func (o FlyHTTPHealthcheck) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlyHTTPHealthcheck) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.Scheme) {
		toSerialize["scheme"] = o.Scheme
	}
	if !IsNil(o.TlsServerName) {
		toSerialize["tls_server_name"] = o.TlsServerName
	}
	if !IsNil(o.TlsSkipVerify) {
		toSerialize["tls_skip_verify"] = o.TlsSkipVerify
	}
	return toSerialize, nil
}

type NullableFlyHTTPHealthcheck struct {
	value *FlyHTTPHealthcheck
	isSet bool
}

func (v NullableFlyHTTPHealthcheck) Get() *FlyHTTPHealthcheck {
	return v.value
}

func (v *NullableFlyHTTPHealthcheck) Set(val *FlyHTTPHealthcheck) {
	v.value = val
	v.isSet = true
}

func (v NullableFlyHTTPHealthcheck) IsSet() bool {
	return v.isSet
}

func (v *NullableFlyHTTPHealthcheck) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlyHTTPHealthcheck(val *FlyHTTPHealthcheck) *NullableFlyHTTPHealthcheck {
	return &NullableFlyHTTPHealthcheck{value: val, isSet: true}
}

func (v NullableFlyHTTPHealthcheck) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlyHTTPHealthcheck) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


