/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the FlyStopConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlyStopConfig{}

// FlyStopConfig struct for FlyStopConfig
type FlyStopConfig struct {
	Signal *string `json:"signal,omitempty"`
	Timeout *FlyDuration `json:"timeout,omitempty"`
}

// NewFlyStopConfig instantiates a new FlyStopConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlyStopConfig() *FlyStopConfig {
	this := FlyStopConfig{}
	return &this
}

// NewFlyStopConfigWithDefaults instantiates a new FlyStopConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlyStopConfigWithDefaults() *FlyStopConfig {
	this := FlyStopConfig{}
	return &this
}

// GetSignal returns the Signal field value if set, zero value otherwise.
func (o *FlyStopConfig) GetSignal() string {
	if o == nil || IsNil(o.Signal) {
		var ret string
		return ret
	}
	return *o.Signal
}

// GetSignalOk returns a tuple with the Signal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyStopConfig) GetSignalOk() (*string, bool) {
	if o == nil || IsNil(o.Signal) {
		return nil, false
	}
	return o.Signal, true
}

// HasSignal returns a boolean if a field has been set.
func (o *FlyStopConfig) HasSignal() bool {
	if o != nil && !IsNil(o.Signal) {
		return true
	}

	return false
}

// SetSignal gets a reference to the given string and assigns it to the Signal field.
func (o *FlyStopConfig) SetSignal(v string) {
	o.Signal = &v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *FlyStopConfig) GetTimeout() FlyDuration {
	if o == nil || IsNil(o.Timeout) {
		var ret FlyDuration
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlyStopConfig) GetTimeoutOk() (*FlyDuration, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *FlyStopConfig) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given FlyDuration and assigns it to the Timeout field.
func (o *FlyStopConfig) SetTimeout(v FlyDuration) {
	o.Timeout = &v
}

func (o FlyStopConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlyStopConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Signal) {
		toSerialize["signal"] = o.Signal
	}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	return toSerialize, nil
}

type NullableFlyStopConfig struct {
	value *FlyStopConfig
	isSet bool
}

func (v NullableFlyStopConfig) Get() *FlyStopConfig {
	return v.value
}

func (v *NullableFlyStopConfig) Set(val *FlyStopConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableFlyStopConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableFlyStopConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlyStopConfig(val *FlyStopConfig) *NullableFlyStopConfig {
	return &NullableFlyStopConfig{value: val, isSet: true}
}

func (v NullableFlyStopConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlyStopConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


