/*
Machines API

This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/) for how to get started, more information about each endpoint, parameter descriptions, and examples.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package machines

import (
	"encoding/json"
)

// checks if the SetSecretkeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetSecretkeyResponse{}

// SetSecretkeyResponse struct for SetSecretkeyResponse
type SetSecretkeyResponse struct {
	Name *string `json:"name,omitempty"`
	PublicKey []int32 `json:"public_key,omitempty"`
	Type *string `json:"type,omitempty"`
	Version *int32 `json:"version,omitempty"`
}

// NewSetSecretkeyResponse instantiates a new SetSecretkeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetSecretkeyResponse() *SetSecretkeyResponse {
	this := SetSecretkeyResponse{}
	return &this
}

// NewSetSecretkeyResponseWithDefaults instantiates a new SetSecretkeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetSecretkeyResponseWithDefaults() *SetSecretkeyResponse {
	this := SetSecretkeyResponse{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SetSecretkeyResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetSecretkeyResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SetSecretkeyResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SetSecretkeyResponse) SetName(v string) {
	o.Name = &v
}

// GetPublicKey returns the PublicKey field value if set, zero value otherwise.
func (o *SetSecretkeyResponse) GetPublicKey() []int32 {
	if o == nil || IsNil(o.PublicKey) {
		var ret []int32
		return ret
	}
	return o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetSecretkeyResponse) GetPublicKeyOk() ([]int32, bool) {
	if o == nil || IsNil(o.PublicKey) {
		return nil, false
	}
	return o.PublicKey, true
}

// HasPublicKey returns a boolean if a field has been set.
func (o *SetSecretkeyResponse) HasPublicKey() bool {
	if o != nil && !IsNil(o.PublicKey) {
		return true
	}

	return false
}

// SetPublicKey gets a reference to the given []int32 and assigns it to the PublicKey field.
func (o *SetSecretkeyResponse) SetPublicKey(v []int32) {
	o.PublicKey = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SetSecretkeyResponse) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetSecretkeyResponse) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SetSecretkeyResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SetSecretkeyResponse) SetType(v string) {
	o.Type = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *SetSecretkeyResponse) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetSecretkeyResponse) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *SetSecretkeyResponse) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *SetSecretkeyResponse) SetVersion(v int32) {
	o.Version = &v
}

func (o SetSecretkeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetSecretkeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PublicKey) {
		toSerialize["public_key"] = o.PublicKey
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableSetSecretkeyResponse struct {
	value *SetSecretkeyResponse
	isSet bool
}

func (v NullableSetSecretkeyResponse) Get() *SetSecretkeyResponse {
	return v.value
}

func (v *NullableSetSecretkeyResponse) Set(val *SetSecretkeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSetSecretkeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSetSecretkeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetSecretkeyResponse(val *SetSecretkeyResponse) *NullableSetSecretkeyResponse {
	return &NullableSetSecretkeyResponse{value: val, isSet: true}
}

func (v NullableSetSecretkeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetSecretkeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


